################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

[de]
languageName = "Deutsch"
languageCode = "de"
contentDir = "content/deutsch"
weight = 1
